version: '3'

services:
  timescale:
    image: timescale/timescaledb:2.6.0-pg14
    volumes:
      - 'timescale_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
volumes:
  timescale_data:
    driver: local
